#DB config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shopping
    username: root
    password: root  
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
#Eureka config    
#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://localhost:8761/eureka/

#Actuator config      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  metrics:
    enable:
      all: true

#Circuit breaker config
resilience4j:
  circuitbreaker:
    instances:
     productService:
        register-health-indicator: true
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 50000
        record-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
          
     inventoryService:
        register-health-indicator: true
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        record-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
